# Generated by Django 4.1.13 on 2026-09-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_companion', '0003_course_coursesection_lesson_coursequizattempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursequizattempt',
            name='correct_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coursequizattempt',
            name='mistakes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coursequizattempt',
            name='review_data',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='acceptable_answers',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lesson',
            name='learning_type',
            field=models.CharField(default='word', max_length=50),
        ),
    ]
