# Generated by Django 4.1.13 on 2026-09-25 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study_companion', '0004_coursequizattempt_correct_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_sign', models.CharField(max_length=100)),
                ('predicted_sign', models.CharField(blank=True, max_length=100, null=True)),
                ('recognition_confidence', models.FloatField(default=0.0)),
                ('reference_similarity', models.FloatField(blank=True, null=True)),
                ('matched', models.BooleanField(default=False)),
                ('status', models.CharField(default='uncertain', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_attempts', to='study_companion.lesson')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_attempts', to='study_companion.coursesection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
