# Generated by Django 4.1.13 on 2026-09-25 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study_companion', '0005_practiceattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('reference_content', models.TextField()),
                ('reference_concepts_json', models.JSONField(blank=True, default=dict)),
                ('reconstructed_explanation', models.TextField(blank=True, default='')),
                ('raw_recognized_units', models.JSONField(blank=True, default=list)),
                ('explanation_source', models.CharField(choices=[('live', 'Live Webcam'), ('recorded', 'Uploaded Video')], default='live', max_length=20)),
                ('recognition_confidence', models.FloatField(default=0.0)),
                ('concept_coverage', models.FloatField(default=0.0)),
                ('relationship_accuracy', models.FloatField(default=0.0)),
                ('overall_understanding_score', models.FloatField(default=0.0)),
                ('category_summary_json', models.JSONField(blank=True, default=dict)),
                ('status_classification_json', models.JSONField(blank=True, default=dict)),
                ('video_saved', models.BooleanField(default=False)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='concept_videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('corrected_reconstruction', models.TextField(blank=True, null=True)),
                ('corrected_coverage', models.FloatField(blank=True, null=True)),
                ('corrected_relationship_accuracy', models.FloatField(blank=True, null=True)),
                ('teacher_notes', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_review', to='study_companion.conceptassessment')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConceptResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('understood', 'Understood'), ('partially_understood', 'Partially Understood'), ('missing', 'Missing'), ('misconception', 'Possible Misconception')], max_length=30)),
                ('confidence', models.FloatField(default=1.0)),
                ('feedback', models.TextField(blank=True, default='')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='study_companion.conceptassessment')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('attempt_number', models.IntegerField(default=1)),
                ('recognition_confidence', models.FloatField(default=0.0)),
                ('concept_coverage', models.FloatField(default=0.0)),
                ('relationship_accuracy', models.FloatField(default=0.0)),
                ('overall_understanding_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['attempt_number'],
            },
        ),
    ]
